### ISSUE TITLE
changed keyboard layout does not survive reboot

### ISSUE THREAD

**Issue by beta-tester** [raspberrypi/rc_gui#4] opened 2015-10-04 09:08 UTC
according to https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=122060

if i install Raspbian Jessie and use the "Raspberry Pi Configuration" and change the keyboard layout from en-UK to de-DE, the keyboard layout is changed only temporary.
as soon i reboot the Raspberry Pi, all keyboard layout changes gone lost, i made with "Raspberry Pi Configuration"

i have install Raspbian Jessie via NOOBS v1.4.2 and via NOOBS lite v1.4 on a RPi1B and RPi2B.

if i change in NOOBS the keyboard layout, and install Raspbian, then this changed keyboard layout takes affect in the OS - that works and survive reboots
(it is a one-time change via /boot/os_config.json and init.d).
if i change the keyboard layout via raspi-config afterwards the installation of Raspbian, that works as well and survive reboots.
but if i change the keyboard layout via "Raspberry Pi Configuration" the keyboard layout is gone and is back to what ever it was bafore i used "Raspberry Pi Configuration".

**Comment by spl237** [comment] 2015-10-04 09:58
The problem is that for some reason, the command to reload the saved keyboard when X starts up does not seem to be automatically running in every case.

There is a fix for this which involves running the keyboard settings reload in the general autostart settings rather than those in the session manager; this has been tested and found to work, and will be pushed in the next update.

**Comment by spl237** [comment] 2015-10-04 10:06
If you want to try the fix, create the file /home/pi/.config/autostart/lxkeymap.desktop, with the following content:

[Desktop Entry]
Type=Application
Name=lxkeymap
Comment=Load international keyboard settings
NoDisplay=true
Exec=sh /home/pi/.config/lxsession/LXDE-pi/autokey.sh
NotShowIn=GNOME;KDE;XFCE;

**Comment by beta-tester** [comment] 2015-10-04 17:38
yes, that made the change...

1. i made a virgin Raspbian Jessie installation via NOOBS v1.4.2.
2. i tried to change the keyboard layout from en-UK to de-DE, via Raspberry Pi Configuration.
3. rebooted RPi, and the keyboard layout was back to en-UK.

4. i tried to change the keyboard layout from en-UK to de-DE, via Raspberry Pi Configuration.
5. rebooted RPi, and the keyboard layout was back to en-UK.
6. i tried to change the keyboard layout from en-UK to de-DE, via Raspberry Pi Configuration.
7. rebooted RPi, and the keyboard layout was back to en-UK.

8. logged in remotely via SSH and first created a autostart folder:
mkdir -p ~/.config/autostart/
9. created the file with the content you showed:
nano  ~/.config/autostart/lxkeymap.desktop
...
10. rebooted RPi, and the keyboard layout was now on de-DE as i changed at step 6.
11. rebooted RPi, and the keyboard layout was still on de-DE.

so it works.
thanks for the solution, hope it will get be updated soon.

**Comment by spl237** [comment] 2015-10-04 17:52
Thanks for testing; we'll include it in the next release.

**Comment by beta-tester** [comment] 2015-10-27 21:41
a recent update with "sudo apt-get -y upgrade" broke the de-DE key layout settings again, now even with the workaround you showed me before (lxkeymap.desktop).

**Comment by beta-tester** [comment] 2015-10-27 21:47
maybe not the update is now the issue...
if i unplug and plug again my usb-keyboard, the settings switch back to en-UK immediately.
any idea, how to fix that, to have permanent the de-DE settings, that survive a reboot RPi and unplug/plug keyboard?

**Comment by wardjk** [comment] 2015-11-03 22:22
I have the same problem as [beta-tester](https://github.com/beta-tester). In my specific case, I use a KVM switch to connect to the RPi. The selected language doesn't matter. Upon reconnecting the keyboard to the RPi, keyboard layout setting goes back to "United Kingdom - English (UK)".

**Comment by beta-tester** [comment] 2015-11-09 10:19
i opened a new issue for the unplug/plug issue.

**Comment by ilmaisin** [comment] 2015-11-21 23:14
spl237, what do you mean by "next release"? Does it mean that this will be fixed in Raspbian Stretch that will be released in about two years?

You know, this is not an advanced feature, but a basic feature that *should* no question work without a slightest issue.

**Comment by spl237** [comment] 2015-11-22 10:21
We make several releases of Raspbian each year. The fix for this will be in the next one. If you can't wait that long, then it is already in apt and can be downloaded from there using apt-get upgrade, or you can simply apply the fix described in my posting above.

If none of that is acceptable to you, then given the educational aims of the Raspberry Pi project and the free and open-source nature of Raspbian, why not try contributing to the community by fixing it yourself?

**Comment by ilmaisin** [comment] 2015-11-22 11:42
>We make several releases of Raspbian each year. The fix for this will be in the next one. If you can't wait that long, then it is already in apt and can be downloaded from there using apt-get upgrade, or you can simply apply the fix described in my posting above.

Well, I have already done *apt-get upgrade*, but the misbehaviour still continues. The keyboard layout set from raspi-config seems to persist reboots, but the one set from lxde settings per-user basis does not. Does Raspbian's X11 somehow use the console's keyboard layout by default, or how does it work?

> If none of that is acceptable to you, then given the educational aims of the Raspberry Pi project and the free and open-source nature of Raspbian, why not try contributing to the community by fixing it yourself?

Unfortunately I find your answer lacking in internal consistency. The fix should be already committed, but on the other hand I should become a programmer and submit a fix for it? I'm sorry but now I don't understand.

**Comment by spl237** [comment] 2015-11-22 12:39
You say "The keyboard layout set from raspi-config seems to persist reboots, but the one set from lxde settings per-user basis does not."

What exactly do you mean by "the one set from lxde settings per-user basis"? Are you referring to the keyboard setting dialog accessed from the Raspberry Pi Configuration dialog (whose setting does persist across reboots if you have the bug fix referred to above) or something else? Settings made in any fashion other than through the keyboard settings dialog accessed from Raspberry Pi Configuration or from the Mouse and Keyboard Settings application are not supported.

Does your /home/pi/.config/autostart/ directory contain an lxkeymap.desktop file? Or is there one in /etc/xdg/autostart? If not, then you haven't upgraded correctly from apt - if there is, then a keyboard setting made in the Raspberry Pi Configuration application should be persisting over a reboot - this has been extensively tested and is known to work.

**Comment by ilmaisin** [comment] 2015-11-22 14:36
Now it started to function. I had to run *apt-get upgrade* multiple times for some reason. I used the *Mouse and Keyboard Settings* from the menu.

**Comment by huebe** [comment] 2015-11-28 16:34
Just running apt-get upgrade didn't work on my pi, but according to the output the raspberrypi-ui-mods package got held back. Running apt-get dist-upgrade fixed it.

**Closed** 2016-01-05 10:10 UTC

**Comment by AlexanderSavelyev** [comment] 2016-02-21 09:40
I just found the same issue with raspbian 2016-02-09. Running apt-get upgrade did not help me. But after some investigation the file /home/pi/.config/lxkeymap.cfg was found. This file caused the issue with changing keyboard layout after reboot. I removed lxkeymap.cfg (back-up first) and everything started to work.

**Comment by Vaulg** [comment] 2016-02-25 13:26
I had the same problem and running apt-get dist-upgrade fixed it.

**Comment by fabiovix** [comment] 2016-04-02 15:02
spl237, 

Your solution worked perfectly here....tested with Brazilian layout and a Raspberry Pi 2 B running Raspbian Jessie. Thanks !

**Comment by deepakkapoor624** [comment] 2016-08-30 06:25
I have followed your solution of writing lxkeymap.desktop file in Raspberypi3 but it didnt worked.

**Comment by fabiovix** [comment] 2016-08-30 12:03
Hi everyone, 

An update:  in the new version of Raspbian, this issue seems to be fixed without the need for scripts.  I've tested the  2016-03-18-raspbian-jessie.img with success available in:

https://www.raspberrypi.org/downloads/raspbian

**Comment by ShopmoFrank** [comment] 2017-02-09 09:15
Hey there,

It's 2017, I am on a Raspberry Pi 3B and just installed a virgin Raspian Jessie with Pixel (Release 2017-01-11) and am still facing the issue. I did all updates and upgrades. 

A shutdown followed by a regular start keeps the keyboard settings at de_DE. 
A reboot dismisses the changes and sets the keyboard back to en_EN. 
Setting up the file lxkeymap.desktop (followed instructions meticulously) didn't help. 

I am using a bluetooth keyboard. It re-connects automatically after reboot. Only the language settings are being changed back to English.

Any other ideas? What I could do?

Thanks very much
Frank

**Comment by commonhatchetfish** [comment] 2017-02-16 13:59
Same issues as Frank, though I'll add that my BT kb is being reset to UK QWERTY from US Dvorak not just on reboot, but every time it powersaves and reconnects, no pi reboot needed.

**Comment by spl237** [comment] 2017-02-17 09:56
OK, looks as if there may be an issue with how Bluetooth keyboards interact with the driver - I'll have a look when I get a chance.

**Comment by commonhatchetfish** [comment] 2017-02-17 12:27
Quick update: since posting yesterday I've installed RetroPi (via the installer script for raspbian, not a drive image) and if set using retropi's config tool, the setting sticks through reboots and k.b. powersaves. Little drastic as a workaround, but i figured it might be useful info while investigating.

**Comment by karlmortensen** [comment] 2017-02-23 06:34
I can set my keyboard to US English 104 key via `sudo raspi-config`, but it did not survive reboots either. As far as I can tell, I have the latest-greatest. `sudo apt-get dist-upgrade` and `sudo apt-get upgrade` both claimed there were zero packages to install. `uname -a` shows "Linux raspberrypi 4.4.34-v7+ #930 SMP Wed Nov 23 15:20:41 GMT armv71 GNU/Linux". I have a LXinput-setup.desktop file in the place mentioned,  

With a wired keyboard and a wireless mouse, I was having issues with it switching to a UK keyboard every reboot. For me, the thing that fixed it was editing the file /home/pi/.config/lxkeymap.cfg and removing the text "intl" from the "variant =" option. After that, it worked like a charm.

**Comment by spl237** [comment] 2017-02-24 16:08
I believe I have found the issue here. The keymap is loaded by a call to lxkeymap --autostart on boot, but the keymap seems to be lost as soon as a keyboard is disconnected; at initial boot, a Bluetooth keyboard is probably disconnected as it has not yet been woken from sleep, so no keymap loads.

I've modified the Bluetooth plugin for lxpanel (which manages all Bluetooth connections for the desktop) so that lxkeymap --autostart is run whenever a BT keyboard connects. In my testing here, this retains BT keyboard maps over a reboot and when a keyboard sleeps and is rewoken.

We'll push this change out into apt in the near future - if anyone wants it before then, feel free to check out and rebuild lxpanel from the raspberrypi-ui GitHub repo.

**Comment by panzhongxian** [comment] 2017-03-08 16:34
After changing the layout, I typed ~ in terminal and it worked well. But if I changed window to Text Editor immediately and type ~, it was not ~ any more. Is this the same issue?

**Comment by foice** [comment] 2018-02-11 11:27
still have this issue on stretch ... am I alone?

**Comment by Taxicletter** [comment] 2018-02-17 15:14
No, I have the same problem! Every other setting in the Raspberry setting panel is remembered, but not the keyboard layout. I use Stretch from the Google AIYproject.

**Comment by peentoon** [comment] 2018-02-18 19:35
Same here... fresh install of stretch and i noticed that keyboard layout selection is not loaded after reboot.
Neither rpi-upgrade nor apt-get update/upgrade helped.
Was the aforementioned fix ever integrated? Given almost one year of silence, and now 3 new reports in few days, should we think this is a new issue?

**Comment by spl237** [comment] 2018-02-23 18:37
I've just checked this on the current image - if you use the Keyboard Settings dialog (accessed from either the Localisation page on Raspberry Pi Configuration, or the Keyboard tab in Mouse and Keyboard Settings), the setting is saved over reboot and correctly reloaded.

The fixes above were all integrated; if this doesn't work on your image, I suspect you are either setting the keyboard language by some method other than the dialog mentioned above, or something in your startup is broken and no longer loading the keymap at startup. I am not surprised that this doesn't work in the AIY version of Stretch; that's a pretty hacked-about release of Raspbian with known problems.

**Comment by peentoon** [comment] 2018-02-24 11:13
I have configured the keyboard layout via raspiconfig on a fresh install of raspbian stretch downloaded from the official website. hardware is a raspberry pi 3.
this does look like a bug.

**Comment by spl237** [comment] 2018-02-24 11:18
raspi-config is not the correct way to configure the keyboard for the desktop - you need to use the Keyboard Settings dialog, as described above.

**Comment by peentoon** [comment] 2018-02-24 11:19
Indeed, i could work this around by setting the layout via the graphical interface (Main menu > Preferences > Mouse and Keyboard Settings > Keyboard > Keyboard Layout...)

**Comment by peentoon** [comment] 2018-02-24 11:20
But why raspi-config does not work?

**Comment by spl237** [comment] 2018-02-24 11:23
Probably because, like a lot of the code in raspi-config, this particular option is old and ought to be deprecated. raspi-config is only really provided for backward compatibility in the console environment, but it isn't actively maintained - the GUI tool does everything raspi-config does, and is the recommended method for configuration.

**Comment by foice** [comment] 2018-02-24 12:12
I am sorry, this method does not work as well, at least for me on Stretch.

**Comment by spl237** [comment] 2018-02-24 12:28
In that case, something is broken in your image - this method has been repeatedly tested on the Stretch image and it definitely works. Try downloading the latest clean image and see if it works on there; if it does, some change you have made to your image is breaking it.

**Comment by foice** [comment] 2018-02-24 18:26
thanks for this input, but are you suggesting "format c: and reboot" like
in MS windows? sorry but there must be a way (just I do not know it, sorry
for my ignorance) to log what is going on at boot time and see why the US
keyboard is loaded instead of my local one. any idea in this sense?

any how, this is "the" image of stretch from raspberry pi website
https://www.raspberrypi.org/downloads/raspbian/ , no hacks as far as I
know. maybe I have done something to set it incorrectly/inconsistently,
still I was hoping to solve the problem not to format the SD card to solve
it.

**Comment by crowmagnumb** [comment] 2018-04-08 19:03
I have a brand new pure install of ```2018-03-13-raspbian-stretch``` and if I set the keyboard to Dvorak in the GUI raspberry pi config it will only be remembered upon running the GUI again. i.e. after ```startx```. I am booting this pi into the command line and there it is NOT Dvorak. Even if I start the GUI and then "Exit to command line" it reverts back to Qwerty.

**Comment by crowmagnumb** [comment] 2018-04-08 19:13
SOLUTION: Had to edit my config file directly.

```
sudo nano /etc/default/keyboard
```
 and change ```XKBLAYOUT=”gb”``` to read ```XKBLAYOUT=”dvorak”```.

Upon reboot I'm now good to go.

**Comment by Problematician** [comment] 2020-03-24 17:29
I noticed that it is still not working properly after so many updates, since the "Close" tab at the "Keyboard Layout Handler" does not mean OK, SAVE AND CLOSE the window.

My solution was to add two Keyboard Layout Handler to the Taskbar. One of them was set up, so that "Keep System Layouts" was ticked, one was with "Do not Reset Existing Options". In the meantime the one with the "Do not Reset Existing Options" ticked had been filled up with the proper languages I wanted, the other on left as is. Windows closed with Alt + F4 instead of Close button. I also went to Preferences/Keyboard and Mouse menu and changed the Keyboard layout there, so the first and second icon changed, but when pressing the   Ctrl + Shift + CapsLock only the second icon changed. That means the application works, so I hit the key combinations until the first icon showed some text EVDEV or something, then removed it from the task bar. In the same time I added a spacer ater the Keyboard Layout Handler and closed it. The thing got saved after rebooting.

**Comment by golumb** [comment] 2020-11-21 19:36
> My solution was to add two Keyboard Layout Handler to the Taskbar. ...

Thank you, Problematician, that trick worked (nothing else did).

I got buster:
~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
...

I suspect this has something to do with the fact that clicking "Close" in the "Keyboard Layout Handler" dialog, doesn't do anything. You have to click "x" in the top right corner.

**Comment by fluxrider** [comment] 2020-11-28 20:05
The lxpanel plugin xkb seems to not save it's config correctly for us. I resorted to edit the config manually.

Edit `~/.config/lxpanel/LXDE-pi/panels/panel`

Find the xkb plugin entry. Mine on rpi400/RaspberryPiOS looked like this:

```
Plugin {
  type=xkb
  Config {
    Model=pc105
    LayoutsList=us
    VariantsList=,
    ToggleOpt=grp:shift_caps_toggle
  }
}
```

Update it with whatever you want, for me I want display as text instead of flags, and two keyboard layout:
```
Plugin {
  type=xkb
  Config {
    DisplayType=1
    KeepSysLayouts=0
    Model=pc105
    LayoutsList=us,ca
    VariantsList=,multix
    ToggleOpt=grp:shift_caps_toggle
  }
}
```

I deduces the key/value from reading the code at https://github.com/lxde/lxpanel/tree/master/plugins/xkb.
The constructor of the plugin initializes from this config file (and I guess never saves back).
You can get a list of values from `man xkeyboard-config` or by using the troublesome 'Keyboard Layout Handler' UI.
